

### Traer los Posts
GET http://localhost:3001/api/tareas


### Crear los Posts
POST http://localhost:3001/api/tareas
Content-Type: application/json
{
    "titulo": "Nuevo titulo",
    "contenido": "Nuevo contenido",
    "imagen_post": "www.url.com"
}

### Actualizar los Posts
PUT http://localhost:3001/api/tareas/1
Content-Type: application/json
{
    "titulo": "Nuevo titulo",
    "contenido": "Nuevo contenido",
    "imagen_post": "www.url.com"
}

### Borrar los Posts
DELETE http://localhost:3001/api/tareas/1