

### Traer los Posts
GET http://localhost:3001/api/tareas


### Crear los Posts
POST http://localhost:3001/api/tareas
Content-Type: application/json

{
    "titulo": "Tercer titulo",
    "contenido": "Tercer contenido",
    "imagen_post": "www.url.com"
}

### Actualizar los Posts
PUT http://localhost:3001/api/tareas/4
Content-Type: application/json

{
    "titulo": "Cambiando titulo",
    "contenido": "Agregando contenido",
    "imagen_post": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrAfOnAn5iZjMpsg6cEP-q09U_w7YMESWWhA&usqp=CAU"
}

### Borrar los Posts
DELETE http://localhost:3001/api/tareas/1